##########################################################################################################
# 3DFM_BCPop dataset options file for bioSPADE
# Values here determine dataset and experimental details
##########################################################################################################
---
# Directories
mesh_root: '' # location of meshes
stack_root: '' # location of 3d image stacks

##########################################################################################################
# Style Details
##########################################################################################################

powers: '1' # list of powers to sample from
frames: '8' # list of frames to sample from

##########################################################################################################
# Sampling Details
##########################################################################################################

prob_new_mesh: .1
mesh_res: # zxy pitch of meshes
    - 1000.0 # z
    - 621.48 # x
    - 621.48 # y  

random_scale: True # Randomly scale image to augment data


##########################################################################################################
# Sampling Details
##########################################################################################################

crop_xy_sz: # crop stack to this xy size
    - 256 # x
    - 256 # y
    
gt_ignore_neighbour_pxs: False # ignore neighbouring pixels when performing segmentation (This is done when dendrites are thin)

in_Gslices: 9 # number of gen. input slices
in_Dslices: 4 # number of discrim. input slices
in_Sslices: 4 # number of seg. input slices
delta_slice: 1 # number slices to skip when sampling
delta_z: .1 # value to indicate difference between slices
    
batch_size: 4 # batch size for training
samples_per_instance: 1 # number of samples from a single loaded mesh (True batch size = batch_size*sample_per_instance)

seg_batch_size: 4 # batch size used when training the segmentation net
seg_samples_per_instance: 4 # samples per instance used when training segmentation net
seg_train_is_valid: True

##########################################################################################################
# Architecture Details
##########################################################################################################

num_Dconv: 3 # Larger num Dconv because we need larger receptive field

acquire_Frechet_noise: True # Add Frechet noise
acquire_Gaussian_noise: True # Add Gaussian noise

condition_on_power: False # there is only 1 frame averaging
condition_on_frames: False # there is only 1 power

in_dim: '3D'
dim_Dconv: '2D'
dim_Dgram: '3D'
